services:
  postgres_db:
    image: postgres:16-alpine
    container_name: multidata_postgres
    environment:
      POSTGRES_USER: multidata_user
      POSTGRES_PASSWORD: multidata_pass
      POSTGRES_DB: multidata
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  postgres_data: